services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sentiment
      POSTGRES_PASSWORD: sentiment
      POSTGRES_DB: sentiment
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sentiment-api:
    build: .
    environment:
      DB_URL: postgresql+psycopg2://sentiment:sentiment@db:5432/sentiment
      STORAGE_MODE: db
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
